---
- hosts: kraken
  vars:
    kr_repo: https://github.com/kraken-hpc/kraken-layercake.git
    kr_repo_version: "main"
    kr_build_args: "-v -force"
  roles:
    - common
    - kraken_build
    - kraken_tftpboot
    - kraken_build_layer0
    - kraken_state
    - kraken_systemd
    - kraken_dashboard
#    - extras
